import { ScrollView, StyleSheet, Text, View } from 'react-native'
import React from 'react'
import { moderateScale, scale, textScale } from '../../utils/responsiveSizes';

const EnglishContent = () => {
    const Heading = ({ txt, customStyles }) => <Text style={[styles.heading, customStyles]}>{txt}</Text>;
    const Paragraph = ({ txt, customStyles }) => <Text style={[styles.paragraph, customStyles]}>{txt}</Text>;
    const BulletNumber = ({ txt, customStyles }) => {
        return (
            txt.map((e, i) => (
                <View key={i} style={[styles.flexRow, customStyles, { gap: 6 }]}>
                    <Text style={styles.bullet}>{`${++i})`}</Text>
                    <Text style={styles.bullet}>{e}</Text>
                </View>
            ))
        )
    }
    const BulletCircle = ({ txt, customStyles, txtStyles }) => {
        return (
            txt.map((e, i) => (
                <View key={i} style={[styles.flexRow, customStyles, { gap: 6 }]}>
                    <View style={[styles.bulletCrcle, { marginTop: 6 }]} />
                    <Text style={[styles.bullet, txtStyles]}>{e}</Text>
                </View>
            ))
        )
    }

    return (
        <ScrollView contentContainerStyle={{ flexGrow: 1, paddingHorizontal: moderateScale(22) }} showsVerticalScrollIndicator={false}>
            <View style={styles.contentContainer}>
                <Heading txt="Circle Care Terms and Conditions" />
                <Paragraph txt='Circle Care ("Circle Care," "we," or "us") Thank you for visiting our application (the "app"). The following Circle Care Terms and Conditions (the "Terms and Conditions") apply in their entirety when you:' />
                <BulletCircle txt={[
                    'Access or use the application;',
                    'Register as a Circle Care member ("Member") at The Application, which provides you with access to some or all of The App’s activities, content, products, services, surveys, and tests (collectively, the Circle Care Services), as well as various interactive features and services (collectively, the "Interactive Services" and together with the Circle Care Services, the "Services");',
                    'Register for one of our sweepstakes, promotional offers, or contests, as offered from time to time (the "Promotions").'
                ]} />
                <Paragraph customStyles={{ marginTop: 8 }} txt='The Circle Care Application Privacy Policy ("Privacy Policy"), the Circle Care Non-Disclosure and Confidentiality Agreement, other Circle Care operating rules, policies, price schedules (if any), promotion rules, and additional supplemental terms and conditions or documents that may be published from time to time are expressly incorporated herein by reference (collectively, the "Agreement"). Please review the agreement carefully.' />
                <Paragraph txt='YOU MUST AFFIRMATIVELY CONSENT TO USE OUR OFFERINGS, AND BY DOING SO, YOU CONSENT TO THESE TERMS AND CONDITIONS, INCLUDING OUR PRIVACY POLICY. IF YOU DO NOT AGREE TO OUR TERMS AND CONDITIONS, INCLUDING OUR PRIVACY POLICY, IN THEIR ENTIRETY, YOU MAY NOT ACCESS OR OTHERWISE USE THE SERVICES, CONTENT (AS THAT TERM IS DEFINED BELOW), PROMOTIONS, OR APP IN ANY MANNER OR FORM WHATSOEVER.' />
                <Paragraph txt='IF YOU ARE A PARENT OR GUARDIAN AND YOU PROVIDE CONSENT FOR YOUR CHILD TO REGISTER WITH THE APPLICATION, YOU MUST AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS IN RESPECT OF SUCH CHILD’S USE OF THE APPLICATION.' />
                <Paragraph txt='The content appearing on The App is provided for informational purposes only. Much of the content, as well as the member content (as defined below), appearing on The App is provided by third parties. Circle Care shall not be responsible or liable for the accuracy, usefulness, or availability of any Content, Member Content, or other information transmitted or made available by and through The App and/or Services.' />
                <Paragraph txt='Under our Privacy Policy, we will only process your personal information (as defined in the Privacy Policy) in accordance with applicable data protection and privacy laws.' />
                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Scope / Modification of Agreement']} />
                <Paragraph txt='You agree to the terms and conditions outlined in the Agreement with respect to your use of the Services, Content, App, Promotions, Member Content, and/or any other analyses, research, opinions, reports, and/or other information provided by or through the same (collectively, "Circle Care Offerings"). The Agreement constitutes the entire and only agreement between you and Circle Care with respect to your use of the Circle Care Offerings and supersedes all prior or contemporaneous agreements, representations, warranties, and/or understandings with respect to your use of the Circle Care Offerings. Circle Care may, without notice, update, revise, or change the Agreement and the scope and functionality of the Circle Care Offerings, in whole or in part, at any time; provided, however, that any amendment or modification to the arbitration provisions, prohibition on class actions provisions, or any other provisions applicable to dispute resolution (collectively, "Dispute Resolution Provisions") shall not apply to any disputes that arose prior to the applicable amendment or modification. The latest agreement will be posted on The App, and you should review the agreement prior to using the Circle Care offerings. By your continued use of the Circle Care Offerings, you hereby agree to comply with and be bound by all of the terms and conditions contained within the Agreement effective at that time (other than with respect to disputes arising prior to the amendment or modification of the Dispute Resolution Provisions, which shall be governed by the Dispute Resolution Provisions then in effect at the time of the subject dispute). Therefore, you should regularly check The App for any updates and/or changes. You understand and agree that Circle Care is not responsible or liable in any manner whatsoever for your inability to use the Circle Care offerings.' />
                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['No Medical or Psychiatric Therapy']} />
                <Paragraph txt='CIRCLE CARE IS NOT A THERAPEUTIC ORGANIZATION PROVIDER OR FORUM, AND WE DO NOT ENGAGE IN PATIENT DIAGNOSIS OR THE PRACTICE OF MEDICINE. THE CONTENT AND MEMBER CONTENT PRESENTED BY AND THROUGH THE APP AND/OR SERVICES IS IN NO WAY INTENDED AS MEDICAL AND/OR PSYCHIATRIC THERAPY AND IS NOT PROVIDED FOR THE PURPOSE OF DIAGNOSING OR TREATING MEDICAL AND/OR PSYCHIATRIC PROBLEMS OR CONDITIONS, NOR IS IT A SUBSTITUTE FOR MEDICAL AND/OR PSYCHIATRIC TREATMENT AND/OR THERAPY. THE APP AND SERVICES ARE NOT, AND SHOULD NEVER BE, A SUBSTITUTE FOR THE ADVICE OF A LICENSED HEALTHCARE PROVIDER OR MEDICAL PROFESSIONAL. The use of The App and/or services does not establish a doctor-patient relationship. ACCORDINGLY, WHILE COMMUNICATIONS BETWEEN YOU AND CIRCLE CARE ARE COVERED BY OUR PRIVACY POLICY, THEY ARE NOT PROTECTED BY PHYSICIAN-PATIENT PRIVILEGE OR DOCTOR-PATIENT CONFIDENTIALITY. ALL CONTENT AND MEMBER CONTENT THAT IS MADE AVAILABLE BY AND THROUGH THE APP AND/OR SERVICES SHOULD BE DISCUSSED AND CONFIRMED WITH YOUR PHYSICIAN, PSYCHIATRIST, THERAPIST, OR OTHER HEALTHCARE PROVIDER BEFORE ADOPTING ANY WELLNESS PROGRAM, EXERCISE PROGRAM, OR OTHER TREATMENT, WHETHER OFFERED ON THE APP, THROUGH THE SERVICES, OR OTHERWISE. USE OF THE APP, SERVICES, CONTENT, AND MEMBER CONTENT FEATURED THEREIN IS AT YOUR OWN RISK. INFORMATION AND STATEMENTS REGARDING SOME OF THE PRODUCTS AND/OR SERVICES FEATURED BY AND THROUGH THE APP AND/OR SERVICES HAVE NOT BEEN EVALUATED BY THE FOOD AND DRUG ADMINISTRATION AND ARE NOT INTENDED TO DIAGNOSE, TREAT, CURE, OR PREVENT ANY DISEASE OR PSYCHOLOGICAL DISORDER.' />
                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Requirements']} />
                <Paragraph txt='The Circle Care Offerings are not available to:' />
                <BulletCircle txt={[
                    'Any users previously suspended or removed from The App or Services',
                    'ANY PERSONS UNDER THE AGE OF 16 WHOSE REGISTRATION HAS NOT BEEN APPROVED BY A PARENT OR LEGAL GUARDIAN.'
                ]} />
                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Registration/Account/Fees/Billing']} />
                <Paragraph txt='Initially, visitors to The App may be offered a proprietary Circle Care "Assessment or "Track Recommender"." Upon completion, Circle Care may invite the visitor to register on The App to become a member. Visitors may also register for membership or become members by and through their Facebook® or E-mail  accounts, through a Circle Care HealthTM program offered by various healthcare providers, health plans, and/or employers, or through any other means designated by Circle Care.' />
                <Paragraph txt='Circle Care reserves the right, in its sole discretion, to deny membership, as well as any Circle Care offering, to anyone for any reason whatsoever, as permitted by applicable law. The registration data that you must supply on The App in order to obtain access to the Circle Care Offerings as a member may include, without limitation, depending on the method used by you to register: full name; e-mail address; date of birth; home address; telephone number; username and password; where you register via your Facebook® account, your: Facebook® ID; Facebook® profile name; Facebook® profile picture; education history (as included in your Facebook account); interests (as included in your Facebook® account); Facebook® photographs included in your Facebook® account; and any and all other information made available to Circle Care by and through your Facebook® account;. You agree to provide true, accurate, current, and complete registration data and to update your registration data as necessary to maintain it in an up-to-date and accurate fashion. Circle Care will verify and approve all registrants in accordance with its standard verification procedures.' />
                <Paragraph txt='You can access your specific member account on The App using your user name and password, logging in via your Facebook® account and/or E-mail  account, as applicable and where authorized by Circle Care, or through the Circle Care Health program. You are responsible for maintaining the confidentiality of your member account, username, and password and for restricting access to your computer. You agree to accept responsibility for all activities that occur through the use of your member account, username, and password.' />
                <Paragraph txt='If you have reason to believe that your member account is no longer secure (for example, in the event of a loss, theft, or unauthorized disclosure or use of your username, password, or any credit, debit, or charge card number stored), you will notify Circle Care of the problem to avoid possible liability for any unauthorized charges to your account. To access and use some of our services, you will need to pay the applicable fees described on The App for such services, including applicable taxes (the "subscription fees"), unless you are accessing and using the services through a program offered by a Circle Care Health Program Company, in which case the terms of payment, if any, will be established by the Circle Care Health Program Company. When you subscribe for services requiring a payment, you hereby agree to pay the subscription fees in accordance with billing terms in effect at the time the fee or charge becomes payable, and you agree to abide by the Terms and Conditions like any other user or member. See the Payment Policy section below.' />
                <Paragraph txt='We reserve the right to change, suspend, or terminate any account, including any feature, content, or service, at any time for any reason. We may also place limitations on the use of certain services, content, or features and/or limit your access to parts of The App or services without notice or liability.' />
                <Paragraph txt="Circle Care agrees that it will terminate any paid or unpaid subscription to services upon notice from the member. A member's right to use The App is subject to any limits established by Circle Care or by the member's credit card issuer, unless the member is using The App through a Circle Care Health Programme Company, when other payment terms may apply. If payment cannot be charged to a Member's credit card or a Member's charge is returned for any reason, including a chargeback, Circle Care reserves the right to either suspend or terminate the Member's access and account, thereby terminating this Agreement and all obligations of Circle Care hereunder." />
                <Paragraph txt="Circle Care may reject your application and/or terminate your membership at any time and for any reason, in our sole discretion. Such reasons may include, without limitation: where Circle Care believes that you are in any way in breach of the Agreement; and where Circle Care believes that you are, at any time, conducting any unauthorized commercial activity by and through the Services." />
                <Paragraph txt='For purposes of the Agreement, "Facebook®" shall mean Facebook, Inc.,. Facebook® is a registered trademark of Facebook, Inc. Please be advised that Circle Care is not in any way affiliated with Facebook®, and the Circle Care offerings are neither endorsed nor sponsored by Facebook®' />

                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Circle Care']} />
                <Paragraph txt='Circle Care offers its app and services to various healthcare providers, health plans, and/or other organizations and companies. Members, employees, clients, or customers of such Circle Care Health Program Companies may be subject to the payment terms provided by their Circle Care Health Program Company.' />
                <Paragraph txt='By participating in the coaching programme, you consent to the disclosure of this information to any coach with whom you are working. The coach is under a duty to maintain the confidentiality of this information and any other personal information you share with the coach, and the coach may not disclose this information to anyone else unless under a legal requirement to do so.' />

                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Payment Policy']} />
                <Paragraph txt='Access to some sections of the Circle Care application or through certain Circle Care programmes is free, but we charge for some of our products and services on a subscription-based basis. This payment policy applies to users who have purchased a Circle Care subscription plan to access Circle Care through the mobile application.' />

                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={['Overview of Subscription Plans and Payments']} />
                <Paragraph txt='We offer several types of individual plans and gift plans. The pricing terms applicable to your account may vary depending on promotions, the type of subscription, and the term you select at the time of purchase. Most of our subscription plans renew automatically, as described in more detail below. If you have questions regarding your plan after you sign up, please refer to your membership page and the confirmation email that will be sent to you after your purchase.' />
                <Paragraph txt='We may from time to time, at our discretion, offer a 30-day trial period for the yearly and two-year subscription plans, and if you sign up under that offer, you will not be billed for the full term until the end of the 30-day trial period. After the end of any trial period, our subscription plans are billed in one up-front payment for the entire term of the plan you choose. Thus, if you purchase a monthly plan, you will be charged for the full month’s payment at the beginning of each month, and if you purchase a yearly or two-year plan, you will be charged for the entire year or two-year term at the beginning of the term. You will also be able to cancel the yearly or two-year subscription within 30 days after the fee has been charged to your account, in accordance with our cancellation terms. We may use a third-party payment processor to facilitate your payments.' />

                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={['Lifetime Subscription Plans']} />
                <Paragraph txt='Circle Care offers a lifetime subscription plan. A Circle Care Lifetime subscription plan allows you to access the Circle Care services available at the time of your purchase for as long as those services are available. You may not assign a lifetime subscription plan to any other person. Circle Care makes no warranties or representations that any of its services will continue to be available for any period of time, and by purchasing a Lifetime plan, you acknowledge and agree that the Circle Care services could change or terminate at any time in the future.' />

                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={['Refund Policy']} />
                <Paragraph txt='Circle Care offers a 30-day, 100% money-back guarantee for subscriptions for the yearly, two-year, and lifetime plans. The monthly plan is excluded from this offer. You may receive a refund by contacting our customer service team within 30 days of your purchase. Requests made after 30 days will not be eligible. We do not prorate refunds or offer partial refunds except in instances where we have terminated your membership for any reason other than your breach of our terms. Purchases of subscriptions made through the Apple iTunes Store or our iPhone or iPad applications are final and are not eligible for a refund. These purchases are subject to Apple’s terms and payment policy, and Apple’s policy may exclude refunds as well.' />
                <Paragraph txt="Purchases of subscriptions made through the Google Play Store or our Android applications are final and are not eligible for a refund. These purchases are subject to Google Play's terms and payment policy, and Google Play's policy may exclude refunds as well." />

                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={['5) Renewals']} />
                <Paragraph txt='All Circle Care subscriptions made on application, except gift purchases, renew automatically using the payment details on file for your account. If you purchase a subscription with the automatic renewal feature, you agree that we are authorised to use the payment information on file to charge the renewal fee.' />
                <Paragraph txt='The date of automatic renewal of your subscription is shown on your membership page and in the payment confirmation email sent after your initial purchase. You may cancel the automatic renewal feature at any time before the renewal date by following the instructions on your membership page or by contacting our customer service team. Additionally, for annual and two-year subscriptions, we will refund renewal payments in full if you contact our customer service team within 7 days after the renewal payment is made. We do not offer refunds for renewal payments for monthly subscriptions after the monthly subscription fee has been charged to your account.' />
                <Paragraph txt='If you signed up for our services using a promotion discount, fees for your renewal may be higher than your initial rate. Please refer to your membership page or the confirmation email sent after your initial purchase for details regarding the renewal amount and the date of the next renewal.' />


                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={['5) Price Increases']} />
                <Paragraph txt='Our prices may change in the future. We will notify you at the time of any price change and provide you with an opportunity to change or cancel your subscription before applying those changes to your account or changing your payment details in connection with an automatic renewal.' />

                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={['6) Payment Information']} />
                <Paragraph txt='By providing payment information to us, you represent that the payment information is accurate, current, and in your own name or in the name of an individual who has authorised you to use his or her payment information for your subscription purchase.' />
                <Paragraph txt='If you provide someone else’s payment information, you agree that we may make a refund to that person if he or she so requests and if the account is eligible for a refund under our Payment Policy. This may cause an interruption to or termination of your Circle Care services.' />

                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Description of the Content']} />
                <Paragraph txt={`Subject to the terms and conditions of the Agreement, end-users that possess the requisite technology and register as Members shall have the opportunity to view all or some of the quizzes, tests, challenges, and activities (collectively, "Activities''), as well as the media, text, images, graphics, analyses, research, comments, opinions, advice, statements, offers, services, requests, solicitations, user interfaces, audio, video, photographs, trademarks, logos, artwork, news articles, and other content made available by and through The App and/or Services (collectively, and together with the Activities, the "Content"). The content is compiled, distributed, and displayed by Circle Care, as well as by members and other third-party content providers ("Third-Party Providers"). Circle Care does not control the content provided by members and/or third-party providers that is made available by and through the services and/or App. Such members and/or third-party providers are solely responsible for the accuracy, completeness, appropriateness, and/or usefulness of such content. The content should not necessarily be relied upon. Circle Care does not represent or warrant that the content and other information posted by and through the services and/or app is accurate, complete, up-to-date, or appropriate. You understand and agree that Circle Care will not be responsible for, and Circle Care undertakes no responsibility to monitor or otherwise police such content. You agree that Circle Care shall have no obligation to you and incur no liability in connection with any such content. You may find certain content posted by members and/or third-party providers to be outdated, harmful, inaccurate, and/or deceptive. Please use caution, common sense, and safety when using the Circle Care offerings.`} />
                <Paragraph txt='If you would like to register a complaint, notify Circle Care of a dispute, notify Circle Care of any improper use of your content or other information, or notify Circle Care of inaccurate or misleading content appearing on The App or otherwise made available by and through the services, please feel free to contact us.' />

                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Description of the Circle Care Services']} />
                <Paragraph txt='Subject to the terms and conditions of the Agreement including, without limitation, Members shall have access to the Circle Care Services. The Circle Care Services include a series of proprietary Circle Care Activities, challenges and other Content that are designed to empower Members to increase their level of happiness employing a broad range of skills. After a Member completes certain Activities, or attains a certain score in connection therewith, he/she may:' />
                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={[
                    'write a brief description of their experience, attach a photograph depicting some relevant aspect of the applicable Activity (the description and photograph, collectively, the “Activity Post”) and, at the Member’s request, publish the Activity Post on The App and make it viewable by either a chosen group of Members, or all Members;',
                    'publish their Activity Post and related information through their Facebook® account (which shall be viewable on Facebook® by those individuals permitted by the Member’s Facebook® account settings) and',
                    'gain access to more advanced Activities that require completion of certain early stage Activities in order to access.',
                ]} />
                <Paragraph txt='Please note, as disclosed in connection with certain “group” Activities, where a Member engages in a group activity, that Member’s participation may be published on The App, to be viewable by all Members. Members are forbidden from posting website links, buttons, banner ads, co - registration paths, copy or processes for generating actions (“Links”) in any Activity Posts, and/or advertising third party products and/or services within the Circle Care Services. Circle Care reserves the right to prohibit any conduct by Members or remove any Activity Post from the Circle Care Services and/or App at any time and for any reason, in Circle Care’s sole discretion. The reasons for removal may include where Circle Care believes that the Activity Post is unsuitable for the Circle Care Services and/or App for any reason including, without limitation:' />
                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={[
                    'That the Activity Post violates Sections 10 and/or 11 below; and/or',
                    'Where Circle Care believes the activity post, or the applicable member, is otherwise in violation of the Agreement.'
                ]} />
                <Paragraph txt='You understand and agree that Circle Care shall not be liable to you, any end-users or any third party for any claim in connection with your use of, or inability to use, the Circle Care Services.' />


                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Description of the Interactive Services']} />
                <Paragraph txt='Subject to the terms and conditions of the agreement, including, without limitation, those contained in Sections 11 and 12 below, members shall have access to the interactive services. The Interactive Services allow Members to communicate with other Members via comments sections and other interactive areas of The App, as well as via applications and other features that may be made available by Circle Care on third-party social media venues such as Facebook® from time to time. In connection with the Interactive Services, each Member shall be solely responsible for the comments, opinions, statements, offers, propositions, feedback, and other content ("Comments") posted by and through the Interactive Services. Members are forbidden from posting links in any comments and/or advertising third-party products and/or services within the interactive services. Circle Care reserves the right to prohibit any conduct by Members or remove any comments from the Interactive Services and/or App at any time and for any reason, in Circle Care’s sole discretion. The reasons for removal may include where Circle Care believes that the comments posted by a member are unsuitable for the interactive services and/or App for any reason, including, without limitation:' />
                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={['That the comments violate sections 11 and/or12 below; and/or', 'Where Circle Care believes the comments, or the applicable member, is otherwise in violation of the agreement.']} />
                <Paragraph txt='You understand and agree that Circle Care shall not be liable to you, any end-users or any third party for any claim in connection with your use of, or inability to use, the interactive services.' />


                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Member Interactions/Comments/Activity Posts']} />
                <Paragraph txt='As part of your use of Circle Care and it’s services, you may upload, post, distribute, disseminate, or send to us Member Content, including but not limited to photographs, images you have taken, captions, and comments, which we, at our discretion, may post on Circle Care. You hereby grant Circle Care an irrevocable, nonexclusive, transferable, royalty-free worldwide right (including any moral rights) and license to use the Member Content on Circle Care and to promote and advertise Circle Care in any way. In connection with the operation and promotion of Circle Care and it’s services, you agree that Circle Care has the right to copy, cache, modify, publish, display, distribute, translate, create derivative works from, and store the Member Content, regardless of the medium, technology, or form in which it is used. For example, Circle Care may use the member content to promote Circle Care and services as part of a book, screen option, demonstration, or brochure.' />
                <Paragraph txt='You also warrant that if you are not the holder of any such rights, the holder of such rights has completely and effectively waived all such rights and validly and irrevocably granted you the right to grant the license stated above. You acknowledge and agree that you are solely responsible for the form, content, and accuracy of any member content. You are responsible for your own postings and the consequences of your postings. You are solely responsible for your interactions with other app users, including, but not limited to, members and third-party providers. Because we are not involved in app-user interactions, in the event that you have a dispute with one or more app-users, members, and/or third-party providers, you hereby release Circle Care including, but not limited to, its officers, directors, members, shareholders, agents, subsidiaries, and employees, from any and all claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of, or in any way connected with, such disputes. Circle Care reserves the right, but has no obligation, to monitor disputes between you and other app users, members, and/or third-party providers. The Services contain comments and activity posts (collectively, "Member Content") that are provided directly by members. Those members are solely responsible for the accuracy, completeness, appropriateness, and/or usefulness of such member content.' />
                <Paragraph txt='Circle Care does not represent or warrant that the Member Content posted by and through the Circle Care application is accurate, complete, or appropriate. You may find certain member content offensive, harmful, inaccurate, and/or deceptive. Please use caution, common sense, and safety when using the services and/or application . You understand and agree that Circle Care shall not be liable to you, any end-d through the application is accurate, complete, or appropriate. You may find certain member content offensive, harmful, inaccurate, and/or deceptive. Please use caution, common sense, and safety when using the services and/or site. You understand and agree that Circle Care shall not be liable to you, any end-users, or any third party for any claim in connection with any member content.' />
                <Paragraph txt='Circle Care does not accept unsolicited ideas, works, or other materials, and you acknowledge that you are responsible for and bear all risk as to the use or distribution of any such ideas, works, or materials.' />

                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Member Content Terms of Use and Restrictions']} />
                <Paragraph txt='As a member, you agree that you are solely responsible for the member content and/or other information that you publish, transmit, and/or post on and through Circle Care and/or services. You agree to use the application to Circle Care and/or services in a manner consistent with any and all applicable laws, rules, and regulations. In connection with your use of Circle Care and/or services, you agree not to:' />
                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={[
                    'Display any telephone numbers, street addresses, URLs, e-mail addresses, or confidential information of any third-party;',
                    'Display any audio files, text, photographs, videos, or other images containing confidential information.',
                    'Display any audio files, text, photographs, videos, or other images that may be deemed indecent or obscene in your community, as defined under applicable law.',
                    'Impersonate any person or entity.',
                    '"Stalk" or otherwise harass any person.',
                    'Engage in any unauthorised advertising or commercial solicitation of application third-parties;',
                    'Transmit any chain letters, spam, or junk e-mail;',
                    'Express or imply that any statements that you make are endorsed by Circle Care™, without our specific prior written consent;',
                    'Harvest or collect the personal information of other members or other persons, whether or not for commercial purposes, without their express consent;',
                    'Use any robot, spider, application search or retrieval application, or other manual or automatic device or process to retrieve, index, "data mine," or in any way reproduce or circumvent the navigational structure or presentation of Circle Care or its contents;',
                    'Post, distribute, or reproduce in any way any copyrighted material, trademarks, service marks, trade secrets, patents, domain names, or other proprietary information without obtaining the prior consent of the owner of such proprietary rights;',
                    'Remove any copyright, trademark, or other proprietary rights notices contained on Circle Care;',
                    'Interfere with or disrupt any of the services, applications, and/or servers or networks connected to them;',
                    'Post, offer for download, e-mail, or otherwise transmit any material that contains software viruses or any other computer code, files, or programmes designed to interrupt, destroy, or limit the functionality of any computer software, hardware, or telecommunications equipment;',
                    'Post, offer for download, transmit, promote, or otherwise make available any software, product, or service that is illegal or that violates the rights of a third-party, including, but not limited to, spyware, adware, programmes designed to send unsolicited advertisements (i.e., "spam-ware"), services that send unsolicited advertisements, programmes designed to initiate "denial of service" attacks, mail bomb programmes, and programmes designed to gain unauthorised access to networks on the Internet;',
                    '"Frame" or "mirror" any part of Circle Care, without our prior written authorization;',
                    'Use metatags, codes, or other devices containing any reference to Circle Care, the Services, and/or Circle Care in order to direct any person to any other application for any purpose; and/or',
                    'Modify, adapt, sublicense, translate, sell, reverse engineer, decipher, decompile, or otherwise disassemble any portion of the services and/or application or any software used on or for the services and/or application.'
                ]} />
                <Paragraph txt='Engaging in any of the aforementioned prohibited practices shall be deemed a breach of the Agreement and may result in the immediate termination of your membership without notice, at the sole discretion of Circle Care. Circle Care reserves the right to pursue any and all legal remedies against members that engage in the aforementioned prohibited conduct.s' />


                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Requirements']} />
                <Paragraph txt='As a Member, you are granted a non-exclusive, non-transferable, revocable, and limited licence to access and use the Circle Care Offerings and certain third-party Member Content in accordance with the Agreement. Circle Care may terminate this licence at any time for any reason. Unless otherwise expressly authorised by Circle Care, you may only use the Circle Care offerings and third-party member content for your own personal use. No part of the Circle Care Offerings or third-party Member Content may be reproduced in any form or incorporated into any information retrieval system, electronic or mechanical. You may not use, copy, emulate, clone, rent, lease, sell, modify, decompile, disassemble, reverse engineer, or transfer the Circle Care Offerings, third-party Member Content, and/or any portion thereof. You may not create any "derivative works" by altering any aspect of the Circle Care Offerings and/or third-party Member Content. You may not use the Circle Care Offerings and/or third-party member content in conjunction with any other third-party content. You may not use any automated means or form of scraping or data extraction to access, query, or otherwise collect content or other information from Circle Care. You may not exploit any aspect of the Circle Care offerings and/or third-party member content for any commercial purposes not expressly permitted by Circle Care. You further agree to indemnify and hold harmless Circle Care for your failure to comply with this Section 14. Circle Care reserves any rights not explicitly granted in the Agreement. YOU AGREE THAT Circle Care, IN ITS SOLE DISCRETION, MAY TERMINATE YOUR USE OF Circle Care OFFERINGS AND REMOVE AND DISCARD ANY CONTENT WITHIN CIRCLE CARE FOR ANY REASON, INCLUDING, WITHOUT LIMITATION, FOR LACK OF USE OR IF Circle Care BELIEVES THAT YOU HAVE VIOLATED OR ACTED INCONSISTENTLY WITH THE LETTER OR SPIRIT OF THE TERMS AND CONDIT Circle Care MAY ALSO, IN ITS SOLE DISCRETION AND AT ANY TIME, DISCONTINUE PROVIDING THE SITE TO CIRCLE CARE AND Circle Care OFFERINGS OR ANY PART THEREOF, WITH OR WITHOUT NOTICE. YOU AGREE THAT ANY TERMINATION OF YOUR ACCESS TO THE SITE TO CIRCLE CARE AND Circle Care OFFERINGS UNDER ANY PROVISION OF THESE TERMS AND CONDITIONS MAY BE EFFECTED WITHOUT PRIOR NOTICE, AND YOU ACKNOWLEDGE AND AGREE THAT Circle Care MAY IMMEDIATELY DEACTIVATE OR DELETE YOUR MEMBER CONTENT AND/OR BAR ANY FURTHER ACCESS TO SUCH FILES, OR Circle Care OFFERINGS. YOU AGREE FURTHER THAT Circle Care SHALL NOT BE LIABLE TO YOU OR ANY THIRD-PARTY FOR ANY TERMINATION OF YOUR ACCESS TO Circle Care OFFERINGS. THE TERMS AND CONDITIONS WILL CONTINUE TO APPLY TO YOUR PAST USE OF THE Circle Care OFFERINGS. TERMINATION OF YOUR ACCESS TO AND USE OF THE SITE TO CIRCLE CARE AND Circle Care OFFERINGS SHALL NOT RELIEVE YOU OF ANY OBLIGATIONS ARISING OR ACCRUING PRIOR TO SUCH TERMINATION OR LIMIT ANY LIABILITY THAT YOU OTHERWISE MAY HAVE TO Circle Care.' />


                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Proprietary Rights']} />
                <Paragraph txt='All third-party Member Content and other material posted or made available by and through the Circle Care Offerings, including, but not limited to, the design, selection, arrangement, and coordination of such Circle Care Offerings, is owned by or licenced to Circle Care and is protected under applicable copyright, trademark, and other proprietary (including, but not limited to, intellectual property) rights. Except as expressly provided in the Agreement, no part of the Circle Care Offerings and/or third-party Member Content may be reproduced, recorded, retransmitted, sold, rented, broadcast, distributed, published, uploaded, posted, publicly displayed, altered to make new works, performed, digitised, compiled, translated, or transmitted in any way to any other computer, application, or other medium, or for any commercial purpose, without Circle Care’s prior express written consent. Except as expressly provided in the Agreement, you are not granted any rights or licence to patents, copyrights, trade secrets, rights of publicity, service marks, or trademarks with respect to any of the Circle Care Offerings, third-party Member Content, or any document, software, services, or other materials viewed at or through the same. The posting of information or material by and through Circle Care, any member, or any third-party provider does not constitute a waiver of any right in or to such information and materials. Circle Care reserves all rights not expressly granted in the Agreement. The "Circle Care" name and logo are trademarks of Circle Care. All custom graphics, icons, and service names are trademarks and/or copyrights of Circle Care. All other trademarks are the property of their respective owners. The use of any Circle Care trademarks, service marks, copyrights, patents, trade secrets, domain names, and/or other proprietary rights without Circle Care’s express written consent is strictly prohibited.' />

                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Bypassing or Disabling any Portion of Circle Care Offerings or Software']} />
                <Paragraph txt='You may not use any device, software, or routine to interfere with or attempt to interfere with the proper working of the Circle Care offerings. You may not take any action that imposes an unreasonable or disproportionately large load on the Circle Care offerings infrastructure. If you bypass or disable any portion of the Circle Care Offerings or associated software, including, without limitation, the blocking of cookies or blocking the operation of any other Circle Care systems, you are in violation of the Agreement, and Circle Care may suspend or terminate your use of the Circle Care offerings without notice. Termination of your access to the Circle Care offerings will not excuse you from any criminal or other civil liability that may result from your actions.' />

                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Indemnification']} />
                <Paragraph txt='You agree to indemnify and hold Circle Care, its parents and subsidiaries, and each of their respective members, officers, directors, employees, agents, co-branders, content licensors, and/or other partners harmless from and against any and all claims, expenses (including reasonable attorneys’ fees), damages, suits, costs, demands, and/or judgements whatsoever, made by any third party due to or arising out of:' />
                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={[
                    'Your use of any of the Circle Care offerings',
                    'Your breach of the Agreement',
                    'Your violation of any rights of another individual and/or entity;',
                    'Any dispute between you and any member, third-party provider, or other third party;',
                    'Your member content and',
                    'Any dispute between you and Facebook® '
                ]} />
                <Paragraph txt='The provisions of this Section 17 are for the benefit of Circle Care, its parents, subsidiaries, and/or affiliates, and each of their respective officers, directors, members, employees, agents, shareholders, licensors, suppliers, and/or attorneys. Each of these individuals and entities shall have the right to assert and enforce these provisions directly against you on its own behalf.' />

                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Disclaimer of Warranties']} />
                <Paragraph txt='THE Circle Care offerings, MEMBER CONTENT, AND/OR ANY OTHER Circle Care PRODUCTS AND/OR SERVICES ARE PROVIDED TO YOU ON AN "AS IS" AND "AS AVAILABLE" BASIS. ANY AND ALL WARRANTIES, EXPRESS AND/OR IMPLIED, ARE DISCLAIMED TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW (INCLUDING, BUT NOT LIMITED TO, THE DISCLAIMER OF ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OF INTELLECTUAL PROPERTY, AND/OR FITNESS FOR A PARTICULAR PURPOSE). In particular, but not as a limitation thereof, Circle Care MAKES NO WARRANTY THAT THE Circle Care OFFERINGS, MEMBER CONTENT, AND/OR ANY OTHER Circle Care PRODUCTS AND/OR SERVICES:' />
                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={[
                    'WILL MEET YOUR REQUIREMENTS;',
                    'WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE OR THAT DEFECTS WILL BE CORRECTED;',
                    'WILL BE FREE OF VIRUSES, WORMS, TROJAN HORSES, OR OTHER HARMFUL COMPONENTS OR DESTRUCTIVE PROGRAMMES;',
                    'WILL HAVE SECURITY METHODS EMPLOYED THAT WILL BE SUFFICIENT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF SAME, OR AGAINST INFRINGEMENT;',
                    'WILL RESULT IN ANY SPECIFIC HAPPINESS, MENTAL HEALTH, PSYCHIATRIC OR OTHER BENEFIT OR RELATED OUTCOME; AND/OR',
                    'WILL BE ACCURATE OR RELIABLE. THE Circle Care OFFERINGS, MEMBER CONTENT, AND/OR ANY OTHER Circle Care PRODUCTS AND/OR SERVICES MAY CONTAIN BUGS, ERRORS, PROBLEMS, OR OTHER LIMITATIONS.'
                ]} />
                <Paragraph txt='Circle Care WILL NOT BE LIABLE FOR THE AVAILABILITY OF THE UNDERLYING INTERNET CONNECTION ASSOCIATED WITH CIRCLE CARE. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM Circle Care, ANY MEMBERS, THIRD-PARTY PROVIDERS, OR OTHERWISE THROUGH OR FROM THE Circle Care OFFERINGS AND/OR MEMBER CONTENT, SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE AGREEMENT.' />

                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Limitation of Liability']} />
                <Paragraph txt='YOU EXPRESSLY UNDERSTAND AND AGREE THAT Circle Care SHALL NOT BE LIABLE TO YOU OR ANY THIRD-PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, AND/OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR PAIN AND SUFFERING, PERSONAL INJURY OR WRONGFUL DEATH, LOSS OF INCOME, LOSS OF CONSORTIUM, BUSINESS INTERRUPTION, OR DAMAGES FOR LOSS OF PROFITS, GOODWILL, LOSS OF DATA, OR OTHER INTANGIBLE LOSS TO THE FULLEST EXTENT PERMISSIBLE BY LAW, Circle Care ALSO SHALL NOT BE LIABLE TO YOU OR ANY THIRD-PARTY FOR:' />
                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={[
                    'THE USE OR THE INABILITY TO USE THE Circle Care OFFERINGS, MEMBER CONTENT, AND/OR ANY OTHER Circle Care PRODUCTS AND/OR SERVICES;',
                    'THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION, CONTENT, AND/OR ANY OTHER Circle Care PRODUCTS AND/OR SERVICES PURCHASED OR OBTAINED FROM OR THROUGH THE Circle Care OFFERINGS AND/OR MEMBER CONTENT;',
                    'THE FAILURE TO REALISE ANY SPECIFIC HAPPINESS, MENTAL HEALTH, PSYCHIATRIC OR OTHER BENEFIT OR RELATED OUTCOME; AND',
                    'ANY OTHER MATTER RELATING TO THE Circle Care OFFERINGS, MEMBER CONTENT, AND/OR ANY OTHER Circle Care PRODUCTS AND/OR SERVICES.'
                ]} />
                <Paragraph txt='THIS LIMITATION APPLIES TO ALL CAUSES OF ACTION IN THE AGGREGATE, INCLUDING, BUT NOT LIMITED TO, SECURITIES LAW VIOLATIONS, BREACH OF CONTRACT, BREACH OF WARRANTY, NEGLIGENCE, STRICT LIABILITY, MEDICAL AND OTHER MALPRACTICE, MISREPRESENTATION, AND ANY AND ALL OTHER TORTS. YOU HEREBY RELEASE Circle Care FROM ANY AND ALL OBLIGATIONS, LIABILITIES, AND CLAIMS IN EXCESS OF THE LIMITATIONS STATED HEREIN. IF APPLICABLE LAW DOES NOT PERMIT SUCH LIMITATION, NO ACTION, REGARDLESS OF FORM, ARISING OUT OF YOUR USE OF THE Circle Care OFFERINGS, MEMBER CONTENT, AND/OR ANY OTHER Circle Care PRODUCTS AND/OR SERVICES MAY BE BROUGHT BY YOU OR Circle Care MORE THAN ONE (1) YEAR FOLLOWING THE EVENT WHICH GAVE RISE TO THE CAUSE OF ACTION. THE NEGATION OF DAMAGES SET FORTH ABOVE IS A FUNDAMENTAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN YOU AND Circle Care. ACCESS TO THE Circle Care OFFERINGS, MEMBER CONTENT, AND/OR ANY OTHER Circle Care PRODUCTS AND/OR SERVICES WOULD NOT BE PROVIDED TO YOU WITHOUT SUCH LIMITATIONS. SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS ON LIABILITY, AND IN SUCH JURISDICTIONS, Circle Care’s liability shall be limited to the maximum extent permitted by law.' />


                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Third-Party Websites']} />
                <Paragraph txt='The Circle Care Offerings contain links to other websites on the Internet that are owned and operated by third-parties, including third-party providers. In some instances, these websites may be cooperating websites on the Internet that are owned and operated by third-parties, including third-party providers. In some instances, these websites may be co-branded, and the third-parties are entitled to use Circle Care’s name and logo on their third-party websites. Circle Care does not control the information, products, or services available on these third-party websites. The inclusion of co-branding and/or links does not imply endorsement by Circle Care of the applicable website or any association with the website’s operators. Because Circle Care has no control over such websites and resources, you agree that Circle Care is not responsible or liable for the availability or operation of such external websites, for any material located on or available from any such websites, or for the protection of your data privacy by third-parties. Any dealings with, or participation in promotions offered by, advertisers or third-party providers featured on Circle Care, including the payment and delivery of related goods or services, and any other terms, conditions, warranties, or representations associated with such dealings or promotions, are solely between you and the applicable Third-Party Provider, advertiser, or other third-party, as applicable. You further agree that Circle Care shall not be responsible or liable, directly or indirectly, for any loss or damage caused by the use of or reliance on any such material available on or through any such site or any such dealings or promotions.' />

                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={['Member Information']} />
                <Paragraph txt='Except where expressly provided otherwise by us in the Agreement and subject to the Privacy Policy, all comments, content, information, and/or materials that you submit through or in association with this application and/or the Circle Care Offerings, including, without limitation, the Member Content, shall be subject to the Privacy Policy. For a copy of the privacy policy, please click here. By submitting such member content and/or materials to us, you are subject to the Privacy Policy:' />
                <BulletCircle txtStyles={{ fontWeight: '600' }} txt={[
                    'Represent and warrant that Circle Care’s use of your submission does not and will not breach any Agreement, violate any law, or infringe any third-party’s rights and is true and accurate in all respects;',
                    'Agree that Circle Care is free to use, in any manner, all or part of such Member Content and/or materials on an unrestricted basis without the obligation to notify, identify, or compensate you or anyone else; and Grant Circle Care all necessary rights, including a waiver of all copyright, trademark, service marks, privacy, right of publicity, and moral rights, to use all Member Content and/or materials, in whole or in part, or as a derivative work, without any duty by Circle Care to anyone whatsoever.'
                ]} />

                <Paragraph customStyles={{ marginTop: 10, marginBottom: 4, fontWeight: 'bold' }} txt='Copyright Policy/DMCA Compliance' />
                <Paragraph txt='Circle Care reserves the right to terminate the membership of any member who repeatedly infringes upon third-party copyright rights. If you believe that a copyrighted work has been copied and/or posted on or via Circle Care and/or services in a way that constitutes copyright infringement, you should provide Circle Care with the following information:' />
                <BulletCircle txtStyles={{ fontWeight: 'bold' }} txt={[
                    'An electronic or physical signature of the person authorised to act on behalf of the owner of the copyrighted work;',
                    'An identification and location on Circle Care (or otherwise) of the copyrighted work that you claim has been infringed upon;',
                    'A written statement by you that you have a good faith belief that the disputed use is not authorised by the owner, its agent, or the law;',
                    'Your name and contact information, such as telephone number or e-mail address,',
                    'A statement by you that the above information in your notice is accurate and, under penalty of perjury, that you are the copyright owner or authorised to act on the copyright owner’s behalf.',
                ]} />
            </View>
        </ScrollView>
    )
}

export default EnglishContent

const styles = StyleSheet.create({
    contentContainer: {
        paddingTop: 20,
        // gap: 20
    },
    // typography
    heading: {
        fontSize: textScale(15),
        color: "#576B74",
        fontWeight: 'bold',
        marginBottom: 16,
    },
    paragraph: {
        fontSize: textScale(15),
        color: "#576B74",
        marginBottom: 16,
    },
    bullet: {
        fontSize: textScale(15),
        color: "#576B74",
        marginBottom: 8,
    },
    bulletCrcle: {
        width: 6,
        height: 6,
        borderRadius: scale(50),
        backgroundColor: '#576B74',
        marginTop: textScale(5)
    },
    flexRow: {
        flexDirection: 'row',
        alignItems: 'flex-start'
    },
})